"""empty message

Revision ID: 9204ae902a7a
Revises: cc6e67231df0
Create Date: 2019-12-03 19:59:30.216595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9204ae902a7a'
down_revision = 'cc6e67231df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id'])
    op.drop_column('employee', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_ibfk_1', 'employee', 'department', ['department'], ['id'])
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###
